# Generated by Django 3.0.11 on 2021-01-24 14:51

from django.db import migrations, models
import django_extensions.db.fields
import gallery.users.models
import gallery.users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(storage=gallery.users.storage.OverwriteStorage(), upload_to=gallery.users.models.image_path)),
                ('visible', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('caption', models.TextField(max_length=511)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
