apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: production
  name: retain-azure-disk
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  storageaccounttype: StandardSSD_LRS  # For real application, it could be better to use
  kind: Managed
