apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: production
  name: media-azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: pv-secrets
    shareName: aksshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=200  # as in compose/production/django/Dockerfile
  - gid=200
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: media-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: media-azurefile
  resources:
    requests:
      storage: 5Gi
