apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: postgres-backups
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default  # managed-premium is preferred however expensive.
  resources:
    requests:
      storage: 1Gi
status: {}
