name: Master-CI

on:
  push:
    branches: [ "master"]
    paths-ignore: [ "docs/**" ]

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  CR_URL: "${{ secrets.CR_URL }}"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build the Stack
        run: docker-compose -f production.yml build

      - name: Push Images
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/push-images.sh"
          "${GITHUB_WORKSPACE}/.github/scripts/push-images.sh"
